return {
        VI = {
            Search = "Tìm kiếm...", ConfigSaved = "Đã lưu config", ConfigLoaded = "Đã tải config",
            Theme = "Đã đổi theme", RainbowOn = "Rainbow BẬT", RainbowOff = "Rainbow TẮT",
            Target = "Đã chọn target", Save = "Lưu", Load = "Tải", Delete = "Xóa",
            Refresh = "Làm mới", PlayerList = "Danh sách người chơi", ConfigManager = "Quản lý Config",
            AccentColor = "Màu Accent", None = "Không", Toggle = "Bật/Tắt", Hold = "Giữ",
            Progress = "Tiến độ", Image = "Hình ảnh", Success = "Thành công", Error = "Lỗi",
            Warning = "Cảnh báo", Info = "Thông tin", Applied = "Đã áp dụng config",
        },
        EN = {
            Search = "Search...", ConfigSaved = "Config saved", ConfigLoaded = "Config loaded",
            Theme = "Theme changed", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Target selected", Save = "Save", Load = "Load", Delete = "Delete",
            Refresh = "Refresh", PlayerList = "Player List", ConfigManager = "Config Manager",
            AccentColor = "Accent Color", None = "None", Toggle = "Toggle", Hold = "Hold",
            Progress = "Progress", Image = "Image", Success = "Success", Error = "Error",
            Warning = "Warning", Info = "Info", Applied = "Config applied",
        },
        ZH = {
            Search = "搜索...", ConfigSaved = "配置已保存", ConfigLoaded = "配置已加载",
            Theme = "主题已更改", RainbowOn = "彩虹 开", RainbowOff = "彩虹 关",
            Target = "已选择目标", Save = "保存", Load = "加载", Delete = "删除",
            Refresh = "刷新", PlayerList = "玩家列表", ConfigManager = "配置管理",
            AccentColor = "强调色", None = "无", Toggle = "切换", Hold = "按住",
            Progress = "进度", Image = "图片", Success = "成功", Error = "错误",
            Warning = "警告", Info = "信息", Applied = "配置已应用",
        },
        JA = {
            Search = "検索...", ConfigSaved = "設定を保存しました", ConfigLoaded = "設定を読み込みました",
            Theme = "テーマを変更しました", RainbowOn = "レインボー ON", RainbowOff = "レインボー OFF",
            Target = "ターゲットを選択", Save = "保存", Load = "読込", Delete = "削除",
            Refresh = "更新", PlayerList = "プレイヤーリスト", ConfigManager = "設定管理",
            AccentColor = "アクセントカラー", None = "なし", Toggle = "切替", Hold = "長押し",
            Progress = "進捗", Image = "画像", Success = "成功", Error = "エラー",
            Warning = "警告", Info = "情報", Applied = "設定を適用しました",
        },
        KO = {
            Search = "검색...", ConfigSaved = "설정 저장됨", ConfigLoaded = "설정 불러옴",
            Theme = "테마 변경됨", RainbowOn = "레인보우 켜짐", RainbowOff = "레인보우 꺼짐",
            Target = "대상 선택됨", Save = "저장", Load = "불러오기", Delete = "삭제",
            Refresh = "새로고침", PlayerList = "플레이어 목록", ConfigManager = "설정 관리",
            AccentColor = "강조 색상", None = "없음", Toggle = "토글", Hold = "홀드",
            Progress = "진행", Image = "이미지", Success = "성공", Error = "오류",
            Warning = "경고", Info = "정보", Applied = "설정 적용됨",
        },
        TH = {
            Search = "ค้นหา...", ConfigSaved = "บันทึกการตั้งค่าแล้ว", ConfigLoaded = "โหลดการตั้งค่าแล้ว",
            Theme = "เปลี่ยนธีมแล้ว", RainbowOn = "เรนโบว์ เปิด", RainbowOff = "เรนโบว์ ปิด",
            Target = "เลือกเป้าหมายแล้ว", Save = "บันทึก", Load = "โหลด", Delete = "ลบ",
            Refresh = "รีเฟรช", PlayerList = "รายชื่อผู้เล่น", ConfigManager = "จัดการการตั้งค่า",
            AccentColor = "สีเน้น", None = "ไม่มี", Toggle = "สลับ", Hold = "กดค้าง",
            Progress = "ความคืบหน้า", Image = "รูปภาพ", Success = "สำเร็จ", Error = "ข้อผิดพลาด",
            Warning = "คำเตือน", Info = "ข้อมูล", Applied = "ใช้การตั้งค่าแล้ว",
        },
        ID = {
            Search = "Cari...", ConfigSaved = "Config disimpan", ConfigLoaded = "Config dimuat",
            Theme = "Tema diubah", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Target dipilih", Save = "Simpan", Load = "Muat", Delete = "Hapus",
            Refresh = "Segarkan", PlayerList = "Daftar Pemain", ConfigManager = "Manajer Config",
            AccentColor = "Warna Aksen", None = "Tidak ada", Toggle = "Alihkan", Hold = "Tahan",
            Progress = "Progres", Image = "Gambar", Success = "Berhasil", Error = "Kesalahan",
            Warning = "Peringatan", Info = "Info", Applied = "Config diterapkan",
        },
        MS = {
            Search = "Cari...", ConfigSaved = "Config disimpan", ConfigLoaded = "Config dimuatkan",
            Theme = "Tema ditukar", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Sasaran dipilih", Save = "Simpan", Load = "Muat", Delete = "Padam",
            Refresh = "Muat semula", PlayerList = "Senarai Pemain", ConfigManager = "Pengurus Config",
            AccentColor = "Warna Aksen", None = "Tiada", Toggle = "Togol", Hold = "Tahan",
            Progress = "Kemajuan", Image = "Imej", Success = "Berjaya", Error = "Ralat",
            Warning = "Amaran", Info = "Maklumat", Applied = "Config digunakan",
        },
        TL = {
            Search = "Maghanap...", ConfigSaved = "Na-save ang config", ConfigLoaded = "Na-load ang config",
            Theme = "Napalitan ang theme", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Napili ang target", Save = "I-save", Load = "I-load", Delete = "Tanggalin",
            Refresh = "I-refresh", PlayerList = "Listahan ng Player", ConfigManager = "Config Manager",
            AccentColor = "Accent Color", None = "Wala", Toggle = "I-toggle", Hold = "Hold",
            Progress = "Progreso", Image = "Imahe", Success = "Tagumpay", Error = "Error",
            Warning = "Babala", Info = "Impormasyon", Applied = "Na-apply ang config",
        },
        HI = {
            Search = "खोजें...", ConfigSaved = "कॉन्फ़िग सहेजा गया", ConfigLoaded = "कॉन्फ़िग लोड हुआ",
            Theme = "थीम बदली गई", RainbowOn = "रेनबो चालू", RainbowOff = "रेनबो बंद",
            Target = "लक्ष्य चुना गया", Save = "सहेजें", Load = "लोड", Delete = "हटाएं",
            Refresh = "रीफ़्रेश", PlayerList = "प्लेयर सूची", ConfigManager = "कॉन्फ़िग प्रबंधक",
            AccentColor = "एक्सेंट रंग", None = "कोई नहीं", Toggle = "टॉगल", Hold = "होल्ड",
            Progress = "प्रगति", Image = "छवि", Success = "सफल", Error = "त्रुटि",
            Warning = "चेतावनी", Info = "जानकारी", Applied = "कॉन्फ़िग लागू",
        },
        AR = {
            Search = "...بحث", ConfigSaved = "تم حفظ الإعدادات", ConfigLoaded = "تم تحميل الإعدادات",
            Theme = "تم تغيير السمة", RainbowOn = "قوس قزح تشغيل", RainbowOff = "قوس قزح إيقاف",
            Target = "تم اختيار الهدف", Save = "حفظ", Load = "تحميل", Delete = "حذف",
            Refresh = "تحديث", PlayerList = "قائمة اللاعبين", ConfigManager = "إدارة الإعدادات",
            AccentColor = "لون التمييز", None = "لا شيء", Toggle = "تبديل", Hold = "ضغط مستمر",
            Progress = "التقدم", Image = "صورة", Success = "نجاح", Error = "خطأ",
            Warning = "تحذير", Info = "معلومات", Applied = "تم تطبيق الإعدادات",
        },
        RU = {
            Search = "Поиск...", ConfigSaved = "Конфиг сохранён", ConfigLoaded = "Конфиг загружен",
            Theme = "Тема изменена", RainbowOn = "Радуга ВКЛ", RainbowOff = "Радуга ВЫКЛ",
            Target = "Цель выбрана", Save = "Сохранить", Load = "Загрузить", Delete = "Удалить",
            Refresh = "Обновить", PlayerList = "Список игроков", ConfigManager = "Менеджер конфигов",
            AccentColor = "Акцентный цвет", None = "Нет", Toggle = "Переключить", Hold = "Удерживать",
            Progress = "Прогресс", Image = "Изображение", Success = "Успех", Error = "Ошибка",
            Warning = "Предупреждение", Info = "Инфо", Applied = "Конфиг применён",
        },
        UK = {
            Search = "Пошук...", ConfigSaved = "Конфіг збережено", ConfigLoaded = "Конфіг завантажено",
            Theme = "Тему змінено", RainbowOn = "Веселка УВІМК", RainbowOff = "Веселка ВИМК",
            Target = "Ціль обрано", Save = "Зберегти", Load = "Завантажити", Delete = "Видалити",
            Refresh = "Оновити", PlayerList = "Список гравців", ConfigManager = "Менеджер конфігів",
            AccentColor = "Акцентний колір", None = "Немає", Toggle = "Перемкнути", Hold = "Утримувати",
            Progress = "Прогрес", Image = "Зображення", Success = "Успіх", Error = "Помилка",
            Warning = "Попередження", Info = "Інфо", Applied = "Конфіг застосовано",
        },
        FR = {
            Search = "Rechercher...", ConfigSaved = "Config enregistrée", ConfigLoaded = "Config chargée",
            Theme = "Thème changé", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Cible sélectionnée", Save = "Enregistrer", Load = "Charger", Delete = "Supprimer",
            Refresh = "Actualiser", PlayerList = "Liste des joueurs", ConfigManager = "Gestionnaire de config",
            AccentColor = "Couleur accent", None = "Aucun", Toggle = "Basculer", Hold = "Maintenir",
            Progress = "Progression", Image = "Image", Success = "Succès", Error = "Erreur",
            Warning = "Avertissement", Info = "Info", Applied = "Config appliquée",
        },
        DE = {
            Search = "Suchen...", ConfigSaved = "Config gespeichert", ConfigLoaded = "Config geladen",
            Theme = "Theme geändert", RainbowOn = "Rainbow AN", RainbowOff = "Rainbow AUS",
            Target = "Ziel ausgewählt", Save = "Speichern", Load = "Laden", Delete = "Löschen",
            Refresh = "Aktualisieren", PlayerList = "Spielerliste", ConfigManager = "Config-Manager",
            AccentColor = "Akzentfarbe", None = "Keine", Toggle = "Umschalten", Hold = "Halten",
            Progress = "Fortschritt", Image = "Bild", Success = "Erfolg", Error = "Fehler",
            Warning = "Warnung", Info = "Info", Applied = "Config angewendet",
        },
        ES = {
            Search = "Buscar...", ConfigSaved = "Config guardada", ConfigLoaded = "Config cargada",
            Theme = "Tema cambiado", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Objetivo seleccionado", Save = "Guardar", Load = "Cargar", Delete = "Eliminar",
            Refresh = "Actualizar", PlayerList = "Lista de jugadores", ConfigManager = "Gestor de config",
            AccentColor = "Color de acento", None = "Ninguno", Toggle = "Alternar", Hold = "Mantener",
            Progress = "Progreso", Image = "Imagen", Success = "Éxito", Error = "Error",
            Warning = "Advertencia", Info = "Info", Applied = "Config aplicada",
        },
        PT = {
            Search = "Pesquisar...", ConfigSaved = "Config salva", ConfigLoaded = "Config carregada",
            Theme = "Tema alterado", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Alvo selecionado", Save = "Salvar", Load = "Carregar", Delete = "Excluir",
            Refresh = "Atualizar", PlayerList = "Lista de jogadores", ConfigManager = "Gerenciador de config",
            AccentColor = "Cor de destaque", None = "Nenhum", Toggle = "Alternar", Hold = "Segurar",
            Progress = "Progresso", Image = "Imagem", Success = "Sucesso", Error = "Erro",
            Warning = "Aviso", Info = "Info", Applied = "Config aplicada",
        },
        IT = {
            Search = "Cerca...", ConfigSaved = "Config salvata", ConfigLoaded = "Config caricata",
            Theme = "Tema cambiato", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Bersaglio selezionato", Save = "Salva", Load = "Carica", Delete = "Elimina",
            Refresh = "Aggiorna", PlayerList = "Lista giocatori", ConfigManager = "Gestore config",
            AccentColor = "Colore accento", None = "Nessuno", Toggle = "Attiva/Disattiva", Hold = "Tieni premuto",
            Progress = "Progresso", Image = "Immagine", Success = "Successo", Error = "Errore",
            Warning = "Avviso", Info = "Info", Applied = "Config applicata",
        },
        TR = {
            Search = "Ara...", ConfigSaved = "Config kaydedildi", ConfigLoaded = "Config yüklendi",
            Theme = "Tema değiştirildi", RainbowOn = "Rainbow AÇIK", RainbowOff = "Rainbow KAPALI",
            Target = "Hedef seçildi", Save = "Kaydet", Load = "Yükle", Delete = "Sil",
            Refresh = "Yenile", PlayerList = "Oyuncu Listesi", ConfigManager = "Config Yöneticisi",
            AccentColor = "Vurgu Rengi", None = "Yok", Toggle = "Aç/Kapat", Hold = "Basılı Tut",
            Progress = "İlerleme", Image = "Görsel", Success = "Başarılı", Error = "Hata",
            Warning = "Uyarı", Info = "Bilgi", Applied = "Config uygulandı",
        },
        PL = {
            Search = "Szukaj...", ConfigSaved = "Config zapisany", ConfigLoaded = "Config wczytany",
            Theme = "Motyw zmieniony", RainbowOn = "Rainbow WŁ", RainbowOff = "Rainbow WYŁ",
            Target = "Cel wybrany", Save = "Zapisz", Load = "Wczytaj", Delete = "Usuń",
            Refresh = "Odśwież", PlayerList = "Lista graczy", ConfigManager = "Menedżer config",
            AccentColor = "Kolor akcentu", None = "Brak", Toggle = "Przełącz", Hold = "Przytrzymaj",
            Progress = "Postęp", Image = "Obraz", Success = "Sukces", Error = "Błąd",
            Warning = "Ostrzeżenie", Info = "Info", Applied = "Config zastosowany",
        },
        NL = {
            Search = "Zoeken...", ConfigSaved = "Config opgeslagen", ConfigLoaded = "Config geladen",
            Theme = "Thema gewijzigd", RainbowOn = "Rainbow AAN", RainbowOff = "Rainbow UIT",
            Target = "Doel geselecteerd", Save = "Opslaan", Load = "Laden", Delete = "Verwijderen",
            Refresh = "Vernieuwen", PlayerList = "Spelerslijst", ConfigManager = "Configbeheer",
            AccentColor = "Accentkleur", None = "Geen", Toggle = "Schakelen", Hold = "Vasthouden",
            Progress = "Voortgang", Image = "Afbeelding", Success = "Succes", Error = "Fout",
            Warning = "Waarschuwing", Info = "Info", Applied = "Config toegepast",
        },
        SV = {
            Search = "Sök...", ConfigSaved = "Config sparad", ConfigLoaded = "Config laddad",
            Theme = "Tema ändrat", RainbowOn = "Rainbow PÅ", RainbowOff = "Rainbow AV",
            Target = "Mål valt", Save = "Spara", Load = "Ladda", Delete = "Radera",
            Refresh = "Uppdatera", PlayerList = "Spellista", ConfigManager = "Config-hanterare",
            AccentColor = "Accentfärg", None = "Ingen", Toggle = "Växla", Hold = "Håll",
            Progress = "Framsteg", Image = "Bild", Success = "Lyckades", Error = "Fel",
            Warning = "Varning", Info = "Info", Applied = "Config tillämpad",
        },
        NO = {
            Search = "Søk...", ConfigSaved = "Config lagret", ConfigLoaded = "Config lastet",
            Theme = "Tema endret", RainbowOn = "Rainbow PÅ", RainbowOff = "Rainbow AV",
            Target = "Mål valgt", Save = "Lagre", Load = "Last", Delete = "Slett",
            Refresh = "Oppdater", PlayerList = "Spillerliste", ConfigManager = "Config-behandler",
            AccentColor = "Aksentfarge", None = "Ingen", Toggle = "Veksle", Hold = "Hold",
            Progress = "Fremdrift", Image = "Bilde", Success = "Vellykket", Error = "Feil",
            Warning = "Advarsel", Info = "Info", Applied = "Config brukt",
        },
        DA = {
            Search = "Søg...", ConfigSaved = "Config gemt", ConfigLoaded = "Config indlæst",
            Theme = "Tema ændret", RainbowOn = "Rainbow TIL", RainbowOff = "Rainbow FRA",
            Target = "Mål valgt", Save = "Gem", Load = "Indlæs", Delete = "Slet",
            Refresh = "Opdater", PlayerList = "Spilliste", ConfigManager = "Config-manager",
            AccentColor = "Accentfarve", None = "Ingen", Toggle = "Skift", Hold = "Hold",
            Progress = "Fremgang", Image = "Billede", Success = "Succes", Error = "Fejl",
            Warning = "Advarsel", Info = "Info", Applied = "Config anvendt",
        },
        FI = {
            Search = "Haku...", ConfigSaved = "Config tallennettu", ConfigLoaded = "Config ladattu",
            Theme = "Teema vaihdettu", RainbowOn = "Rainbow PÄÄLLÄ", RainbowOff = "Rainbow POIS",
            Target = "Kohde valittu", Save = "Tallenna", Load = "Lataa", Delete = "Poista",
            Refresh = "Päivitä", PlayerList = "Pelaajalista", ConfigManager = "Config-hallinta",
            AccentColor = "Korostusväri", None = "Ei mitään", Toggle = "Vaihda", Hold = "Pidä",
            Progress = "Edistyminen", Image = "Kuva", Success = "Onnistui", Error = "Virhe",
            Warning = "Varoitus", Info = "Info", Applied = "Config käytössä",
        },
        CS = {
            Search = "Hledat...", ConfigSaved = "Config uložen", ConfigLoaded = "Config načten",
            Theme = "Motiv změněn", RainbowOn = "Rainbow ZAP", RainbowOff = "Rainbow VYP",
            Target = "Cíl vybrán", Save = "Uložit", Load = "Načíst", Delete = "Smazat",
            Refresh = "Obnovit", PlayerList = "Seznam hráčů", ConfigManager = "Správce config",
            AccentColor = "Barva akcentu", None = "Žádný", Toggle = "Přepnout", Hold = "Držet",
            Progress = "Průběh", Image = "Obrázek", Success = "Úspěch", Error = "Chyba",
            Warning = "Varování", Info = "Info", Applied = "Config použit",
        },
        RO = {
            Search = "Caută...", ConfigSaved = "Config salvat", ConfigLoaded = "Config încărcat",
            Theme = "Temă schimbată", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Țintă selectată", Save = "Salvează", Load = "Încarcă", Delete = "Șterge",
            Refresh = "Reîmprospătează", PlayerList = "Lista jucători", ConfigManager = "Manager config",
            AccentColor = "Culoare accent", None = "Niciunul", Toggle = "Comută", Hold = "Ține",
            Progress = "Progres", Image = "Imagine", Success = "Succes", Error = "Eroare",
            Warning = "Avertisment", Info = "Info", Applied = "Config aplicat",
        },
        HU = {
            Search = "Keresés...", ConfigSaved = "Config mentve", ConfigLoaded = "Config betöltve",
            Theme = "Téma megváltoztatva", RainbowOn = "Rainbow BE", RainbowOff = "Rainbow KI",
            Target = "Cél kiválasztva", Save = "Mentés", Load = "Betöltés", Delete = "Törlés",
            Refresh = "Frissítés", PlayerList = "Játékoslista", ConfigManager = "Config kezelő",
            AccentColor = "Kiemelő szín", None = "Nincs", Toggle = "Váltás", Hold = "Tartás",
            Progress = "Haladás", Image = "Kép", Success = "Siker", Error = "Hiba",
            Warning = "Figyelmeztetés", Info = "Info", Applied = "Config alkalmazva",
        },
        EL = {
            Search = "Αναζήτηση...", ConfigSaved = "Το config αποθηκεύτηκε", ConfigLoaded = "Το config φορτώθηκε",
            Theme = "Το θέμα άλλαξε", RainbowOn = "Rainbow ON", RainbowOff = "Rainbow OFF",
            Target = "Επιλέχθηκε στόχος", Save = "Αποθήκευση", Load = "Φόρτωση", Delete = "Διαγραφή",
            Refresh = "Ανανέωση", PlayerList = "Λίστα παικτών", ConfigManager = "Διαχειριστής config",
            AccentColor = "Χρώμα έμφασης", None = "Κανένα", Toggle = "Εναλλαγή", Hold = "Κράτημα",
            Progress = "Πρόοδος", Image = "Εικόνα", Success = "Επιτυχία", Error = "Σφάλμα",
            Warning = "Προειδοποίηση", Info = "Πληροφορίες", Applied = "Το config εφαρμόστηκε",
        },
}
